server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5432/your db name
    username: your username
    password: your password
  jpa:
    database: postgresql
    properties:
      #      DISABLE JPA VERSION EXCEPTION
      hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update